apiVersion: v1
kind: Secret
metadata:
  name: k8s-manifests-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/your-org/k8s-manifests.git
  username: your-github-username
  password: your-github-token
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: https://your-docker-registry.com
  username: your-registry-username
  password: your-registry-password