apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  labels:
    app: system-management-service
type: Opaque
stringData:
  url: "jdbc:mysql://mysql-service:3306/system_management?useSSL=false&allowPublicKeyRetrieval=true"
  username: "system_user"
  password: "REPLACE_WITH_ACTUAL_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  labels:
    app: system-management-service
type: Opaque
stringData:
  access-key-id: "REPLACE_WITH_AWS_ACCESS_KEY"
  secret-access-key: "REPLACE_WITH_AWS_SECRET_KEY"
---
apiVersion: v1
kind: Secret
metadata:
  name: alert-config
  labels:
    app: system-management-service
type: Opaque
stringData:
  email.recipients: "admin@your-company.com,ops@your-company.com"
  slack.webhook-url: "REPLACE_WITH_SLACK_WEBHOOK_URL"
  teams.webhook-url: "REPLACE_WITH_TEAMS_WEBHOOK_URL"