apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-management-service
  labels:
    app: system-management-service
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system-management-service
  labels:
    app: system-management-service
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system-management-service
  labels:
    app: system-management-service
subjects:
- kind: ServiceAccount
  name: system-management-service
  namespace: system-management
roleRef:
  kind: Role
  name: system-management-service
  apiGroup: rbac.authorization.k8s.io